language: python
notifications:
  email: false
python:
- "2.7"
- "3.4"
install:
# numpy is already installed in the virtualenv
- travis_retry pip install coverage
- travis_retry pip install coveralls
- pip freeze
script:
  - coverage run --source=nrefocus tests/runtests.py
  - coverage report -m
after_success:
  coveralls --verbose
