language: python
python:
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - NUMPY="==1.9.1" TEST="PYTEST"
  - NUMPY="==1.10.1" TEST="PYTEST"
  - NUMPY="==1.11.3" TEST="PYTEST"
  - NUMPY="==1.12.1" TEST="PYTEST"
  - NUMPY="==1.13.1" TEST="PYTEST"
  - NUMPY="==1.14.3" TEST="PYTEST"
  - NUMPY=""  TEST="FLAKE8"
install:
- travis_retry pip install "numpy$NUMPY"
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage
- travis_retry pip install codecov
- travis_retry pip install flake8
- pip freeze
script:
- set -ev
- if [ "${TEST}" == "PYTEST" ]; then
       coverage run --source=nrefocus ./setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 nrefocus;
       flake8 examples;
       flake8 tests;
  fi;
