language: python
python:
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - NUMPY="1.9.1"
  - NUMPY="1.10.1"
  - NUMPY="1.11.3"
  - NUMPY="1.12.1"
  - NUMPY="1.13.1"
install:
- travis_retry pip install "numpy==$NUMPY"
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage
- travis_retry pip install coveralls
- pip freeze
script:
- coverage run --source=nrefocus ./setup.py test
- coverage report -m
after_success:
- coveralls --verbose
