language: python
notifications:
  email: false
python:
- "2.7"
- "3.4"
before_install:
- sudo apt-get update -qq
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get -y install python-numpy; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then sudo apt-get -y install python3-numpy; fi
install:
- travis_retry pip install coverage
- travis_retry pip install coveralls
- pip freeze
script:
  - coverage run --source=nrefocus tests/runtests.py
  - coverage report -m
after_success:
  coveralls --verbose
