language: python
env:
  global:
  - GH_REF: github.com/paulmueller/nrefocus.git
  - secure: IUP1CPflkzUo3YFYQYZqPU03n5eB7lutvGAzFk1AieXsjs2J6bK7gGZZ3Us8flhGcwaeZqjLH4NFUSAlW0mDxeLxWZeCpCF9Z44fcD34zft5+UoB363jGjcyX0xxek7NWKpsfDhKRI96CE8JtvwRGeuFTLgXVD4gJVjWdxX2c6A=
notifications:
  email: false
python:
- '2.7'
- '3.4'
- '3.5'
install:
# numpy is already installed in the virtualenv
- travis_retry pip install coverage
- travis_retry pip install coveralls
- pip freeze
script:
- coverage run --source=nrefocus tests/runtests.py
- coverage report -m
after_success:
- coveralls --verbose
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pip install numpydoc sphinx; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then python doc/deploy_ghpages.py; fi
