language: python
python:
- '3.4'
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - NUMPY="==1.9.1"
  - NUMPY="==1.10.1"
  - NUMPY="==1.11.3"
  - NUMPY="==1.12.1"
  - NUMPY="==1.13.1"
  - NUMPY="==1.14.3"
  - NUMPY=""  TEST="FLAKE8"
install:
- travis_retry pip install "numpy$NUMPY"
- "travis_retry pip install . --only-binary=:all:"
- travis_retry pip install coverage
- travis_retry pip install codecov
- travis_retry pip install flake8
- pip freeze
script:
- coverage run --source=nrefocus ./setup.py test
- coverage report -m
- codecov
- flake8 nrefocus
- flake8 examples
- flake8 tests
deploy:
  provider: pypi
  user: "ci_qpi"
  password:
    secure: "ZG3E94C+IQI6CoKCpC/XV45B3k/dZC+WjSXcQz6YkNQKU9q5giaBp9I/IstD+ci/D2pqRgQj4qJuT9DXDGv8fGwE8iAp1kBfdI1OAxv3516cJiU3tAuwFQ8rvTHQHCpj+eK7qYnzH6PoCHzx5BnCb/SReD6fIBR6kUkBlfOeYb0="
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_cleanup: true
  skip_existing: true

